## Training a Linear Associator to classify space ships and representing characteristics in feature vectors

# 

# 

In [1]:
import pandas as pd
import numpy as np
import random as rnd
import math
import statistics
import matplotlib.pyplot as plt
from sklearn import preprocessing
import regex as re


le = preprocessing.LabelEncoder()


In [2]:
og = pd.DataFrame({'Name': ['Grotz', 'Tlarr', 'Tribok', 'Brogut', 'Glorek', 'Lorif', 'Rallev', 'Willosh', 'Loshar', 'Sarash', 'A2231', 'E7763', 'E9091', 'A0199', 'A1091', 'Daisy', 'Rosehip', 'Gardenia', 'Herb', 'Cinnamon'],
        'Planet of origin': ['Klingon', 'Klingon', 'Klingon', 'Klingon', 'Klingon', 'Romulan', 'Romulan', 'Romulan', 'Romulan', 'Romulan', 'Antarean', 'Antarean', 'Antarean', 'Antarean', 'Antarean', 'Federation', 'Federation', 'Federation', 'Federation', 'Federation'],
        'Warp Drive Vibration Index (Murds)': [6.9, 7.0, 7.3, 7.1, 7.1, 7.3, 7.4, 7.3, 7.2, 7.4, 6.7, 6.8, 6.5, 6.8, 6.7, 6.7, 6.8, 6.5, 6.4, 6.5],
        'Hailing Transponder Freq. (gigaHz)': [1006.4, 994.3, 978.1, 1005.4, 1001.8, 980.4, 977.2, 947.9, 955.8, 960.7, 1010.9, 1033.2, 1025.4, 1066.2, 1015.0, 1050.0, 1055.0, 1045.0, 1065.0, 1055.0],
        'Surface Reflect. (color)': ['Black', 'Black', 'Dark Gray', 'Dark Gray', 'Light Gray', 'Dark Blue', 'Dark Green', 'Light Gray', 'Light Blue', 'Light Gray', 'Pink', 'Orange', 'Light Blue', 'Yellow', 'Light Blue', 'White', 'Light Gray', 'White', 'Light Gray', 'Light Gray'],
        'Ratio of long axis to short axis': [3.5, 2.3, 2.8, 3.0, 1.0, 1.6, 1.8, 1.9, 2.1, 2.3, 1.2, 1.2, 1.1, 1.3, 1.0, 1.9, 2.0, 2.1, 2.6, 1.7],
        'Req. action': ['Hostile', 'Hostile', 'Hostile', 'Hostile', 'Hostile', 'Alert', 'Alert', 'Alert', 'Alert', 'Alert', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly']})

In [3]:
data = pd.DataFrame({'Name': ['Grotz', 'Tlarr', 'Tribok', 'Brogut', 'Glorek', 'Lorif', 'Rallev', 'Willosh', 'Loshar', 'Sarash', 'A2231', 'E7763', 'E9091', 'A0199', 'A1091', 'Daisy', 'Rosehip', 'Gardenia', 'Herb', 'Cinnamon'],
        'Planet of origin': ['Klingon', 'Klingon', 'Klingon', 'Klingon', 'Klingon', 'Romulan', 'Romulan', 'Romulan', 'Romulan', 'Romulan', 'Antarean', 'Antarean', 'Antarean', 'Antarean', 'Antarean', 'Federation', 'Federation', 'Federation', 'Federation', 'Federation'],
        'Warp Drive Vibration Index (Murds)': [6.9, 7.0, 7.3, 7.1, 7.1, 7.3, 7.4, 7.3, 7.2, 7.4, 6.7, 6.8, 6.5, 6.8, 6.7, 6.7, 6.8, 6.5, 6.4, 6.5],
        'Hailing Transponder Freq. (gigaHz)': [1006.4, 994.3, 978.1, 1005.4, 1001.8, 980.4, 977.2, 947.9, 955.8, 960.7, 1010.9, 1033.2, 1025.4, 1066.2, 1015.0, 1050.0, 1055.0, 1045.0, 1065.0, 1055.0],
        'Surface Reflect. (color)': ['Black', 'Black', 'Dark Gray', 'Dark Gray', 'Light Gray', 'Dark Blue', 'Dark Green', 'Light Gray', 'Light Blue', 'Light Gray', 'Pink', 'Orange', 'Light Blue', 'Yellow', 'Light Blue', 'White', 'Light Gray', 'White', 'Light Gray', 'Light Gray'],
        'Ratio of long axis to short axis': [3.5, 2.3, 2.8, 3.0, 1.0, 1.6, 1.8, 1.9, 2.1, 2.3, 1.2, 1.2, 1.1, 1.3, 1.0, 1.9, 2.0, 2.1, 2.6, 1.7],
        'Req. action': ['Hostile', 'Hostile', 'Hostile', 'Hostile', 'Hostile', 'Alert', 'Alert', 'Alert', 'Alert', 'Alert', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly', 'Friendly']})


In [4]:
#transform catagorial variables in numbers
data["Surface Reflect. (color)"] = le.fit_transform(data["Surface Reflect. (color)"])
data['Planet of origin'] = le.fit_transform(data['Planet of origin']) 
data["Req. action"] = le.fit_transform(data['Req. action']) 


In [5]:
#initalizes new column for name encoding
data["Encoded Name"] = np.zeros((20))

In [6]:
data

Name  Planet of origin  Warp Drive Vibration Index (Murds)  \
0      Grotz                 2                                 6.9   
1      Tlarr                 2                                 7.0   
2     Tribok                 2                                 7.3   
3     Brogut                 2                                 7.1   
4     Glorek                 2                                 7.1   
5      Lorif                 3                                 7.3   
6     Rallev                 3                                 7.4   
7    Willosh                 3                                 7.3   
8     Loshar                 3                                 7.2   
9     Sarash                 3                                 7.4   
10     A2231                 0                                 6.7   
11     E7763                 0                                 6.8   
12     E9091                 0                                 6.5   
13     A0199                 0                                 6.8   
14     A1091                 0                                 6.7   
15     Daisy                 1                                 6.7   
16   Rosehip                 1                                 6.8   
17  Gardenia                 1                                 6.5   
18      Herb                 1                                 6.4   
19  Cinnamon                 1                                 6.5   

    Hailing Transponder Freq. (gigaHz)  Surface Reflect. (color)  \
0                               1006.4                         0   
1                                994.3                         0   
2                                978.1                         2   
3                               1005.4                         2   
4                               1001.8                         5   
5                                980.4                         1   
6                                977.2                         3   
7                                947.9                         5   
8                                955.8                         4   
9                                960.7                         5   
10                              1010.9                         7   
11                              1033.2                         6   
12                              1025.4                         4   
13                              1066.2                         9   
14                              1015.0                         4   
15                              1050.0                         8   
16                              1055.0                         5   
17                              1045.0                         8   
18                              1065.0                         5   
19                              1055.0                         5   

    Ratio of long axis to short axis  Req. action  Encoded Name  
0                                3.5            2           0.0  
1                                2.3            2           0.0  
2                                2.8            2           0.0  
3                                3.0            2           0.0  
4                                1.0            2           0.0  
5                                1.6            0           0.0  
6                                1.8            0           0.0  
7                                1.9            0           0.0  
8                                2.1            0           0.0  
9                                2.3            0           0.0  
10                               1.2            1           0.0  
11                               1.2            1           0.0  
12                               1.1            1           0.0  
13                               1.3            1           0.0  
14                               1.0            1           0.0  
15                               1.9            1   

In [7]:
def encode_name(data):
    '''
    Encodes 1,2,3 if name starts with consonant,consonant (1),
    consonant,vowel (2), contains a number (3)
    
    '''
    
    kl_pattern = r'^[bcdfghjklmnpqrstvwxyz]{2}\w*'
    kl_mask = data["Name"].str.findall(kl_pattern,re.IGNORECASE)
    kl_indices = np.where(kl_mask)[0]
    data["Encoded Name"][kl_indices] = 0
    
    ro_pattern = r'\b[b-df-hj-np-tv-z][aeiou]\w*\b'
    ro_mask = data["Name"].str.findall(ro_pattern,re.IGNORECASE)
    ro_indices = np.where(ro_mask)[0]
    data["Encoded Name"][ro_indices] = 1
    
    an_pattern = r'\d+'
    an_mask = data["Name"].str.findall(an_pattern,re.IGNORECASE)
    an_indices = np.where(an_mask)[0]
    data["Encoded Name"][an_indices] = 2
    
    return data
    

In [8]:
encode_name(data)

/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_26586/1871448267.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Encoded Name"][kl_indices] = 0
/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_26586/1871448267.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Encoded Name"][ro_indices] = 1
/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_26586/1871448267.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

Name  Planet of origin  Warp Drive Vibration Index (Murds)  \
0      Grotz                 2                                 6.9   
1      Tlarr                 2                                 7.0   
2     Tribok                 2                                 7.3   
3     Brogut                 2                                 7.1   
4     Glorek                 2                                 7.1   
5      Lorif                 3                                 7.3   
6     Rallev                 3                                 7.4   
7    Willosh                 3                                 7.3   
8     Loshar                 3                                 7.2   
9     Sarash                 3                                 7.4   
10     A2231                 0                                 6.7   
11     E7763                 0                                 6.8   
12     E9091                 0                                 6.5   
13     A0199                 0                                 6.8   
14     A1091                 0                                 6.7   
15     Daisy                 1                                 6.7   
16   Rosehip                 1                                 6.8   
17  Gardenia                 1                                 6.5   
18      Herb                 1                                 6.4   
19  Cinnamon                 1                                 6.5   

    Hailing Transponder Freq. (gigaHz)  Surface Reflect. (color)  \
0                               1006.4                         0   
1                                994.3                         0   
2                                978.1                         2   
3                               1005.4                         2   
4                               1001.8                         5   
5                                980.4                         1   
6                                977.2                         3   
7                                947.9                         5   
8                                955.8                         4   
9                                960.7                         5   
10                              1010.9                         7   
11                              1033.2                         6   
12                              1025.4                         4   
13                              1066.2                         9   
14                              1015.0                         4   
15                              1050.0                         8   
16                              1055.0                         5   
17                              1045.0                         8   
18                              1065.0                         5   
19                              1055.0                         5   

    Ratio of long axis to short axis  Req. action  Encoded Name  
0                                3.5            2           0.0  
1                                2.3            2           0.0  
2                                2.8            2           0.0  
3                                3.0            2           0.0  
4                                1.0            2           0.0  
5                                1.6            0           1.0  
6                                1.8            0           1.0  
7                                1.9            0           1.0  
8                                2.1            0           1.0  
9                                2.3            0           1.0  
10                               1.2            1           2.0  
11                               1.2            1           2.0  
12                               1.1            1           2.0  
13                               1.3            1           2.0  
14                               1.0            1           2.0  
15                               1.9            1   

In [9]:
def normalize(x1):
    x1_norm = (x1 - min(x1)) / (max(x1) - min(x1))
    return x1_norm

In [10]:
#normalizes all numbers in data

data[['Warp Drive Vibration Index (Murds)',
       'Hailing Transponder Freq. (gigaHz)', 'Surface Reflect. (color)',
       'Ratio of long axis to short axis',"Encoded name"]] = data[['Warp Drive Vibration Index (Murds)',
       'Hailing Transponder Freq. (gigaHz)', 'Surface Reflect. (color)',
       'Ratio of long axis to short axis',"Encoded Name"]].apply(normalize)




In [11]:
data

Name  Planet of origin  Warp Drive Vibration Index (Murds)  \
0      Grotz                 2                                 0.5   
1      Tlarr                 2                                 0.6   
2     Tribok                 2                                 0.9   
3     Brogut                 2                                 0.7   
4     Glorek                 2                                 0.7   
5      Lorif                 3                                 0.9   
6     Rallev                 3                                 1.0   
7    Willosh                 3                                 0.9   
8     Loshar                 3                                 0.8   
9     Sarash                 3                                 1.0   
10     A2231                 0                                 0.3   
11     E7763                 0                                 0.4   
12     E9091                 0                                 0.1   
13     A0199                 0                                 0.4   
14     A1091                 0                                 0.3   
15     Daisy                 1                                 0.3   
16   Rosehip                 1                                 0.4   
17  Gardenia                 1                                 0.1   
18      Herb                 1                                 0.0   
19  Cinnamon                 1                                 0.1   

    Hailing Transponder Freq. (gigaHz)  Surface Reflect. (color)  \
0                             0.494505                  0.000000   
1                             0.392223                  0.000000   
2                             0.255283                  0.222222   
3                             0.486052                  0.222222   
4                             0.455621                  0.555556   
5                             0.274725                  0.111111   
6                             0.247675                  0.333333   
7                             0.000000                  0.555556   
8                             0.066779                  0.444444   
9                             0.108199                  0.555556   
10                            0.532544                  0.777778   
11                            0.721048                  0.666667   
12                            0.655114                  0.444444   
13                            1.000000                  1.000000   
14                            0.567202                  0.444444   
15                            0.863060                  0.888889   
16                            0.905325                  0.555556   
17                            0.820795                  0.888889   
18                            0.989856                  0.555556   
19                            0.905325                  0.555556   

    Ratio of long axis to short axis  Req. action  Encoded Name  Encoded name  
0                               1.00            2           0.0           0.0  
1                               0.52            2           0.0           0.0  
2                               0.72            2           0.0           0.0  
3                               0.80            2           0.0           0.0  
4                               0.00            2           0.0           0.0  
5                               0.24            0           1.0           0.5  
6                               0.32            0           1.0           0.5  
7                               0.36            0           1.0           0.5  
8                               0.44            0           1.0           0.5  
9                               0.52            0           1.0           0.5  
10                              0.08            1           2.0           1.0  
11                              0.08            1           2.0           1.0  
12                              0.04            1           2.0     

In [12]:
def planet_codes(n):
    '''
    n: number of zeros after ship code to match number of features
    '''
    klingon = np.zeros((n))
    klingon[0] = 1
    
    romo = np.zeros((n))
    romo[1] = 1
    
    ant = np.zeros((n))
    ant[2] = 1
    
    fed = np.zeros((n))
    fed[3] = 1
   
    x = np.concatenate((np.stack((klingon,) * 5, axis=0), np.stack((romo,) * 5, axis=0), np.stack((ant,) * 5, axis=0),np.stack((fed,) * 5, axis=0) ))
    return x
    
    

In [13]:
def mean_squared_error(pred, gs):
    pred = np.array(pred)
    gs = np.array(gs)
    squared_errors = np.sum((pred - gs) ** 2, axis=1)
    mse = np.mean(squared_errors)
    return mse

In [14]:
def Widrow_Hoff(k, g, g_prime, f, dim):
    length_f = np.linalg.norm(f)
    difference_vector = np.subtract(g, g_prime)
    deltaA = k * (np.outer(difference_vector, np.transpose(f)))
    return deltaA, difference_vector



In [15]:
#takes only columns you want to build A
df = data[data.columns[~data.columns.isin(["Planet of origin",'Name',"Req. action","Encoded Name"])]]
shipz = planet_codes(5)


In [16]:
def LMS_ship (data,ship_code,threshold,k,ksub):
    '''
    Uses the Least Means Squares Algorithm to correct matrix A until
    change in mean square error between iterations is below a threshold.
    
    info: characteristics of ships
    ship_code: encoded planet for ships
    threshold: What the change in mean square error is for simulation to stop
    
    '''
    
    f_set = df.to_numpy()
    g_set = ship_code
    pairs = len(ship_code)
    dim = len(f_set[0])
    
    #intialize A with zeros
    #A = np.zeros((pairs,dim))
    
    pred_list = []
    gs = []
    norms = [0]
    count = 1 #keeps track of how many time while loop occurs, has to start w 1 bc of K
    sq_errors = [1] # keeps track of mean standard error
    all_mse = []
    Errors=[]
    converged = False
    m = len(f_set[0])
    n = len(g_set[0])
    
    A_i = [ np.outer(f_set[i],np.transpose (g_set[i])) for i in range(pairs) ]
    A = np.zeros((m,n))
    for i in range(pairs):
        A = np.add(A, A_i[i])
    
    
    while converged == False:# number of iterations of this loop is number of trials
        randomList = [] #keeps track of which pairs used in one trial
        for i in range(pairs-len(randomList)):
            #make sure a random, but not sequential pair is picked
            #also ensures entire group is being picked from, without replacement
            
            r = rnd.randint(1,pairs-1)
            if r not in randomList: 
                randomList.append(r)
                
                #Pick a random pair t
                f = f_set[r]
                g = g_set[r]
                g_prime = A.dot(f.T)
                
                pred_list.append(g_prime)
                
                #keep tracks of g vectors used
                gs.append(g)

                
                #set K to constant / # of learning trials
                #k = ((1/np.dot(f,f)) - (1/1000)) / trials
                
                #updating of A and predictions
                deltaA, error = Widrow_Hoff(k, g, g_prime, f, dim)
                A = np.add(A, deltaA)
                error_length = np.linalg.norm(error)
                Errors.append(error_length)
                #print("Current Error:", error_length)

                k =  abs(k - ksub)
            
            #continues for loop if pair is already picked
            else:
                continue
            mse = mean_squared_error(pred_list, gs)
            all_mse.append(mse)
            print("Current MSE:", mse)
        #if (abs(error_length) < threshold):
        if (abs(mse) < threshold):
            print("MSE: ", mse)
            #print("Error: ", abs(error_length))
            print("Error Threshold: ", threshold)
            print("Number of trials: ", count)
            
            return A
            converged = True
        
    count = count + 1;
    


In [17]:
A = LMS_ship(df,shipz,0.3,0.85,0.05)

Current MSE: 105.92142025723413
Current MSE: 57.891199164345224
Current MSE: 39.66296979633811
Current MSE: 42.41892770048216
Current MSE: 41.75735389030346
Current MSE: 36.05037523152067
Current MSE: 31.08942769844561
Current MSE: 28.24472161213538
Current MSE: 25.286096709114798
Current MSE: 22.860280900437072
Current MSE: 20.996722567117665
Current MSE: 19.31973783061958
Current MSE: 17.844591642617157
Current MSE: 16.611772682908043
Current MSE: 15.901211357742769
Current MSE: 14.942550168633574
Current MSE: 14.172171164687015
Current MSE: 13.459265117937543
Current MSE: 12.785240650686596
Current MSE: 12.241467034363056
Current MSE: 12.0696023110543
Current MSE: 11.547971109742436
Current MSE: 11.231246600010971
Current MSE: 10.80491400994469
Current MSE: 10.492640146616557
Current MSE: 10.10348249805362
Current MSE: 9.761355837110704
Current MSE: 9.54146498124308
Current MSE: 9.220681197347444
Current MSE: 8.93170774940465
Current MSE: 8.658134365435002
Current MSE: 8.45932797482

In [14]:
#unchanged test_df
ogtest_df = pd.DataFrame({
    'Name': ['______', '_____', 'Lil___', '______', 'Pl__ik', '______', 'Krotork', 'Woshif', 'Kritop', 'C06__', '_____', 'G__rk', '_9e__', '_6___', 'Rash__', 'Sor___', 'A____', 'E4511', '______', 'Mor___'],
    'Planet of origin': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'],
    'Warp Drive Vibration Index (Murds)': [7.3, 6.6, 6.7, None, 7.0, 7.3, 7.0, None, 7.2, 6.7, None, 6.9, 6.6, 6.6, None, None, 6.8, None, None, 6.4],
    'Hailing Transponder Frequency (gigaHz)': [None, 1065.0, 1045.0, 1065.0, 1006.3, 951.4, 1001.8, 971.7, None, None, None, '>1000', None, None, 955.8, '<1000', 1013.3, None, '>1000', 1055.0],
    'Surface Reflect. (color)': ['Light Gray', 'White', 'White', 'Light Color', 'Dark Color', 'Green', 'Light Gray', 'Blue', 'Dark Gray', 'Orange', 'Black', 'Black or Dk Blue', 'Light Blue', 'Orange', 'Light Blue', '_______________', 'Light Color', '_______________', 'Light Color', '_______________'],
    'Ratio of long to short axis': [2.1, 2.1, None, None, None, 1.9, 1.0, 1.7, 2.9, None, 2.6, 3.2, 1.2, None, None, None, 1.0, None, 1.7, None],
    'Req. Action': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '1.0', '?', '?', '?']
})

In [15]:
ogtest_df["Planet"] = np.zeros((20,))

In [16]:
#what I think my guess for the planets are

ogtest_df["Planet"][[0,5,7,18]] = "Romulan" 
ogtest_df["Planet"][[1,2,3,14,19]] = "Federation"
ogtest_df["Planet"][[4,5,6,8,10,11,15]] = "Klingon"
ogtest_df["Planet"][[9,12,13,16,17]] = "Antarean"

/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_33464/878744945.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ogtest_df["Planet"][[0,5,7,18]] = "Romulan"


In [17]:
ogtest_df

Name Planet of origin  Warp Drive Vibration Index (Murds)  \
0    ______                ?                                 7.3   
1     _____                ?                                 6.6   
2    Lil___                ?                                 6.7   
3    ______                ?                                 NaN   
4    Pl__ik                ?                                 7.0   
5    ______                ?                                 7.3   
6   Krotork                ?                                 7.0   
7    Woshif                ?                                 NaN   
8    Kritop                ?                                 7.2   
9     C06__                ?                                 6.7   
10    _____                ?                                 NaN   
11    G__rk                ?                                 6.9   
12    _9e__                ?                                 6.6   
13    _6___                ?                                 6.6   
14   Rash__                ?                                 NaN   
15   Sor___                ?                                 NaN   
16    A____                ?                                 6.8   
17    E4511                ?                                 NaN   
18   ______                ?                                 NaN   
19   Mor___                ?                                 6.4   

   Hailing Transponder Frequency (gigaHz) Surface Reflect. (color)  \
0                                    None               Light Gray   
1                                  1065.0                    White   
2                                  1045.0                    White   
3                                  1065.0              Light Color   
4                                  1006.3               Dark Color   
5                                   951.4                    Green   
6                                  1001.8               Light Gray   
7                                   971.7                     Blue   
8                                    None                Dark Gray   
9                                    None                   Orange   
10                                   None                    Black   
11                                  >1000         Black or Dk Blue   
12                                   None               Light Blue   
13                                   None                   Orange   
14                                  955.8               Light Blue   
15                                  <1000          _______________   
16                                 1013.3              Light Color   
17                                   None          _______________   
18                                  >1000              Light Color   
19                                 1055.0          _______________   

    Ratio of long to short axis Req. Action      Planet  
0                           2.1           ?     Romulan  
1                           2.1           ?  Federation  
2                           NaN           ?  Federation  
3                           NaN           ?  Federation  
4                           NaN           ?     Klingon  
5                           1.9           ?     Klingon  
6                           1.0           ?     Klingon  
7                           1.7           ?     Romulan  
8                           2.9           ?     Klingon  
9                           NaN           ?    Antarean  
10                          2.6           ?     Klingon  
11                          3.2           ?     Klingon  
12                          1.2           ?    Antarean  
13                          NaN           ?    Antarean  
14                          NaN           ?  Federation  
15                          NaN           ?     Klingon  
16                          1.0         1.0    Antarean  
17                          NaN           ?    Antarean  
18   

In [7]:

#fill with average
test_df = pd.DataFrame({
    'Name': ['______', '_____', 'Lil___', '______', 'Pl__ik', '______', 'Krotork', 'Woshif', 'Kritop', 'C06__', '_____', 'G__rk', '_9e__', '_6___', 'Rash__', 'Sor___', 'A____', 'E4511', '______', 'Mor___'],
    
    'Warp Drive Vibration Index (Murds)': [7.3, 6.6, 6.7, None, 7.0, 7.3, 7.0, None, 7.2, 6.7, None, 6.9, 6.6, 6.6, None, None, 6.8, None, None, 6.4],
    'Hailing Transponder Frequency (gigaHz)': [None, 1065.0, 1045.0, 1065.0, 1006.3, 951.4, 1001.8, 971.7, None, None, None, 1033.4, None, None, 955.8, 970.63, 1013.3, None, 1033.4, 1055.0],
    'Surface Reflect. (color)': ['Light Gray', 'White', 'White', 'Light Gray', 'Dark Gray', 'Green', 'Light Gray', 'Blue', 'Dark Gray', 'Orange', 'Black', 'Black', 'Light Blue', 'Orange', 'Light Blue', 'Light Gray', 'Light Gray', 'Light Gray', 'Light Gray', 'Light Gray'],
    'Ratio of long to short axis': [2.1, 2.1, None, None, None, 1.9, 1.0, 1.7, 2.9, None, 2.6, 3.2, 1.2, None, None, None, 1.0, None, 1.7, None],
    
})


In [8]:
#mean of numbers under <1000
np.mean([994.3,978.1,980.4,977.2,947.9,955.8,960.7])

970.6285714285714

In [9]:
#mean of numbers under >1000
np.mean([1006.4,1005.4,1001.8,1010.9,1033.2,1025.4,1066.2,1015,1050,1055,1045,1065,1055])

1033.4076923076923

In [10]:
test_df["Name"] = [0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0]
test_df["Warp Drive Vibration Index (Murds)"][np.isnan(test_df["Warp Drive Vibration Index (Murds)"] )]= np.mean(test_df["Warp Drive Vibration Index (Murds)"])
test_df["Hailing Transponder Frequency (gigaHz)"][np.isnan(test_df["Hailing Transponder Frequency (gigaHz)"])] = np.mean(test_df["Hailing Transponder Frequency (gigaHz)"])
test_df["Ratio of long to short axis"][np.isnan(test_df["Ratio of long to short axis"])] = np.mean(test_df["Ratio of long to short axis"]) 

test_df["Surface Reflect. (color)"] = le.fit_transform(test_df["Surface Reflect. (color)"])


/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_33464/4286190266.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df["Warp Drive Vibration Index (Murds)"][np.isnan(test_df["Warp Drive Vibration Index (Murds)"] )]= np.mean(test_df["Warp Drive Vibration Index (Murds)"])
/var/folders/m1/6jr0fxrx2v3dy832gwp52yc00000gn/T/ipykernel_33464/4286190266.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df["Hailing Transponder Frequency (gigaHz)"][np.isnan(test_df["Hailing Transponder Frequency (gigaHz)"])] = np.mean(test_df["Hailing Transponder Frequency (gigaHz)"])
/var/folders/m1/6jr0fxrx2v3dy832gwp52y

In [52]:
norm_test_df = test_df.apply(normalize)

In [53]:
def input(A,df):
    out = []
    df_numpy = df.to_numpy()
    for i in df_numpy:
        out.append(np.round(A.dot(i),3))
    return out

In [54]:
input(A,norm_test_df)

[array([ 0.142, -0.226,  0.098,  1.031,  0.   ]),
 array([-0.648,  0.559, -0.308,  1.057,  0.   ]),
 array([-0.118,  0.683, -0.311,  0.8  ,  0.   ]),
 array([-0.331,  0.204, -0.191,  1.038,  0.   ]),
 array([ 0.015, -0.146,  0.206,  0.593,  0.   ]),
 array([ 0.413, -0.449,  0.325,  0.617, -0.   ]),
 array([ 0.284, -0.227, -0.384,  0.995,  0.   ]),
 array([ 0.42 ,  0.107,  0.233,  0.064, -0.   ]),
 array([-0.154, -0.096,  0.622,  0.579,  0.   ]),
 array([ 0.325,  0.866, -0.164,  0.322,  0.   ]),
 array([-0.311,  0.048,  0.574,  0.258,  0.   ]),
 array([-0.529,  0.172,  0.776,  0.276,  0.   ]),
 array([ 0.535,  0.689, -0.356,  0.205,  0.   ]),
 array([ 0.237,  0.955, -0.181,  0.268,  0.   ]),
 array([-0.025,  0.01 ,  0.186,  0.477,  0.   ]),
 array([-0.085,  0.077,  0.076,  0.631,  0.   ]),
 array([ 0.755,  0.514, -0.475,  0.437,  0.   ]),
 array([ 0.48 ,  0.683, -0.069,  0.315,  0.   ]),
 array([-0.165,  0.105, -0.205,  0.941,  0.   ]),
 array([-0.701,  0.593, -0.241,  0.749,  0.   ])]

In [55]:
def score(arrays):
    '''
    Assigns a planet guess for each output vector, checks if 
    
    
    '''
    out = []
    for i in range(len(arrays)):
        if arrays[i][0] >= 1:
            out.append("Klingon")
        elif arrays[i][1]>=1:
            out.append("Romulan")
        elif arrays[i][2]>=1:
            out.append("Antarean")
        elif arrays[i][3]>=1:
            out.append("Federation")
           
        elif arrays[i][0]>=0:
            out.append("Klingon")
        elif arrays[i][1]>=0:
            out.append("Romulan")
        elif arrays[i][2]>=0:
            out.append("Antarean")
        elif arrays[i][3]>=0:
            out.append("Federation")
            
    return out

In [56]:
ogtest_df["Guess"] = score(input(A,norm_test_df))

In [78]:
def action(arrays):
    out = []
    for i in range(len(arrays)):
        if arrays[i] == "Klingon":
            out.append("Hostile")
        elif arrays[i] == "Romulan":
            out.append("Alert")
        elif arrays[i] == "Antarean":
            out.append("Friendly")
        elif arrays[i] == "Federation":
            out.append("Friendly")
    return out

In [79]:
ogtest_df["Action"] = action(ogtest_df["Guess"] )

In [80]:
ogtest_df[["Guess","Action"]]

Guess    Action
0   Federation  Friendly
1   Federation  Friendly
2      Romulan     Alert
3   Federation  Friendly
4      Klingon   Hostile
5      Klingon   Hostile
6      Klingon   Hostile
7      Klingon   Hostile
8     Antarean  Friendly
9      Klingon   Hostile
10     Romulan     Alert
11     Romulan     Alert
12     Klingon   Hostile
13     Klingon   Hostile
14     Romulan     Alert
15     Romulan     Alert
16     Klingon   Hostile
17     Klingon   Hostile
18     Romulan     Alert
19     Romulan     Alert

## Write Up

### f vectors
The quantative data(Warp Drive, Hailing Transponder, and Ratio of axis) stayed the same in the feature vectors. To represent the name of the ships, I classified them into if they started with a (consonant, consonant), (consonant,vowel), or (if it contained a number / starts with a capital A or E). In this order, these categories were encoded into 0,1, or 2. The Surface Reflect color was encoded into 0 = Black,Dark Gray = 2, Dark Green = 3,Light Blue = 4, Light Gray = 5, Orange = 6, Pink = 7, White = 8, Yellow = 9. The order of the feature vector followed the order of the data frame (Name, Warp Drive, Hailing Transponder, Surface Reflect, and Ratio of axis). I decided to use all vectors since from my own judgement, it seemed like each planet had something unique in one of the catagories, like Romulan's always having a 3 digit Hailing Transponder Freq. according to the train data. 

### g vectors

I coded the different planets of each ship using one hot encoding.
The number of elements in the vector corresponded with the number number of elements in the feature vector. Klingon was [1,0,0,0,0], Romulan was [0,1,0,0,0], Antarean [0,0,1,0,0], and Federation was [0,0,0,1,0]. To decode the output of the system as guesses for each planet, I either found where the value was 1 and a little more, or found the first positive value that occured and counted that as a 1. Everything else was considered a 0.

In [72]:
wp = ({"Dimension of f": [1,2,3,4,5],
       "Name of Feature": ["Name","Warp Drive Vibration Index (Murds)", "Hailing Transponder Freq.","Surface Reflect","Ratio of Long to Short Axis"],
       "Def of feature": ["(consonant,consonant) = 0, (consonant,vowel) = 1,(contains num or starts w A/E) = 2",
                          "unchanged", "unchanged", "0 = Black,Dark Gray = 2, Dark Green = 3,Light Blue = 4, Light Gray = 5, Orange = 6, Pink = 7, White = 8, Yellow = 9",
                          "unchanged"],
       "Coding Scheme": ["one hot", "standardized values","standardized values","one hot","standardized values"],
       "Missing Data": ["replaced with most common value 0 if not identifiable", "mean","mean", "if >1000 mean of those values, if <1000 mean of those values","most common color, if light color (most common light color), if dark color (most common dark color),mean"]
       
      
      })
write_up = pd.DataFrame(wp)
    
    
    
    


In [73]:
write_up

Dimension of f                     Name of Feature  \
0               1                                Name   
1               2  Warp Drive Vibration Index (Murds)   
2               3           Hailing Transponder Freq.   
3               4                     Surface Reflect   
4               5         Ratio of Long to Short Axis   

                                      Def of feature        Coding Scheme  \
0  (consonant,consonant) = 0, (consonant,vowel) =...              one hot   
1                                          unchanged  standardized values   
2                                          unchanged  standardized values   
3  0 = Black,Dark Gray = 2, Dark Green = 3,Light ...              one hot   
4                                          unchanged  standardized values   

                                        Missing Data  
0  replaced with most common value 0 if not ident...  
1                                               mean  
2                                               mean  
3  if >1000 mean of those values, if <1000 mean o...  
4  most common color, if light color (most common...